id: PA5A057A4
initial_creation_type: input
source_metadata:
  title: Yogasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Yoga
  data entry: 'Ashok Aklujkar '
  contribution to GRETIL: 'Ashok Aklujkar '
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:01:41.302762'
last_modified_at: '2022-03-09T15:01:41.302774'
